import { NextResponse } from "next/server";

export async function GET() {
  
  // Kita tidak pakai variabel lagi di dalam JSON biar pasti benar
  // Pastikan domain ini 'base-vote-alpha' atau 'base-vote-app' (sesuai yang aktif di Vercel)
  const appUrl = "https://base-vote-alpha.vercel.app"; 

  const config = {
    "accountAssociation": {
      "header": "eyJmaWQiOjM0NTk5MywidHlwZSI6ImF1dGgiLCJrZXkiOiIweDRmYmE5NWU0NzcyYmU2ZDM3YTBjOTMxRDAwNTcwRmUyYzk2NzU1MjQifQ",
      "payload": "eyJkb21haW4iOiJiYXNlLXZvdGUtYWxwaGEudmVyY2VsLmFwcCJ9",
      "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAC6XtDGqoxJA4-Bnlh-JjPEqfQooAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA1fIc6Up0QCiRDbFJAPwg_7J0mYr3MNlAu8p0PpTMgtFPzL0dP56HGa8ZeK1ze8jOkgZOWep0LGJSFDNDOhfD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAA-FIQshzFAwL0d7pWaG0gGdybZ63hWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCj0xjHL2wrVK-KwFNP3ZiUyuEyOjdqO4FJ_gttORFj8--Uj_t0kLKuoqh4MKWY8wSKl3OjkoTqmHOSmkcJZB_gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiV1dSM2xLdUszeTZYTmJWZkpZOG1IS2ljdS1UZnNNZmNBZkMtZTRsUHVuTSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS"
    },
    "frame": {
      "version": "1",
      "name": "Base Vote",
      
      // === HARDCODED URL (Lebih Aman) ===
      "iconUrl": "https://base-vote-alpha.vercel.app/icon.png",
      "homeUrl": "https://base-vote-alpha.vercel.app",
      "imageUrl": "https://base-vote-alpha.vercel.app/banner.png", 
      "buttonTitle": "Vote Now",
      "splashImageUrl": "https://base-vote-alpha.vercel.app/base-square.png",
      
      "splashBackgroundColor": "#FFFFFF",
      "webhookUrl": "https://base-vote-alpha.vercel.app/api/webhook",
      
      "primaryCategory": "social",
      "tags": [
        "voting",
        "base"
      ]
    },
    "baseBuilder": {
       "ownerAddress": "0x4fba95e4772be6d37a0c931D00570Fe2c9675524"
    }
  };

  return NextResponse.json(config);
}